apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: steeleye
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: steeleye
spec:
  commonName: steeleye.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: steeleye-ingress
  namespace: steeleye
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts: 
    - steeleye.com
    secretName: selfsigned-cert-tls
  rules:
  - host: steeleye.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: steeleye-svc
          servicePort: 80
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: steeleye
  namespace: steeleye
spec:
  replicas: 2
  selector:
    matchLabels:
      app: steeleye
  template:
    metadata:
      labels:
        app: steeleye
    spec:
      containers:
      - name: steeleye
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: steeleye-svc
  namespace: steeleye
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: steeleye